[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.2",
    "pydantic>=2.12.0",
    "pytest>=8.4.2",
    "uvicorn>=0.37.0",
]
