"""add apple_id and is_active fields update

Revision ID: ba1e0eb44642
Revises: 400d83dc4ba1
Create Date: 2025-10-12 10:35:42.807979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1e0eb44642'
down_revision: Union[str, Sequence[str], None] = '400d83dc4ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'apple_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(op.f('users_apple_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.create_unique_constraint(op.f('users_apple_id_key'), 'users', ['apple_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'apple_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
