"""Add tool_call_data to messages

Revision ID: df59da9b2b44
Revises: 683aa09f9c42
Create Date: 2025-10-25 07:51:26.636813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df59da9b2b44'
down_revision: Union[str, Sequence[str], None] = '683aa09f9c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call_data', sa.JSON(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'tool_call_data')
    # ### end Alembic commands ###
