services:
  postgres:
    image: postgres:16-alpine
    container_name: myapp_postgres_dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: myapp_dev
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d myapp_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
