services:
  postgres:
    image: postgres:16-alpine
    container_name: myapp_postgres_dev
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: myapp_dev
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d myapp_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: myapp_redis_dev
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes
    volumes:
      - ./volume/redis_dev_data:/data

